#pragma once
#define IMAGE_INTERNAL
#include "image_imp.h"
#undef IMAGE_INTERNAL
#include "runtime/command_stream/linear_stream.h"
#include "runtime/helpers/hw_info.h"
#include "runtime/indirect_heap/indirect_heap.h"

namespace L0 {

template <GFXCORE_FAMILY gfxCoreFamily>
struct ImageCoreFamily : public ImageImp {
    using GfxFamily = typename NEO::GfxFamilyMapper<gfxCoreFamily>::GfxFamily;
    using RENDER_SURFACE_STATE = typename GfxFamily::RENDER_SURFACE_STATE;
    using RSS = typename GfxFamily::RENDER_SURFACE_STATE;
    using SURFACE_FORMAT = typename RENDER_SURFACE_STATE::SURFACE_FORMAT;
    using SHADER_CHANNEL_SELECT_ALPHA = typename RENDER_SURFACE_STATE::SHADER_CHANNEL_SELECT_ALPHA;
    using BaseClass = ImageImp;
    using ImageImp::ImageImp;

    const SURFACE_FORMAT SURFACE_FORMAT_UNDEFINED = static_cast<SURFACE_FORMAT>(-1);

    const SURFACE_FORMAT surfaceFormatTable[XE_IMAGE_FORMAT_LAYOUT_MAX + 1][XE_IMAGE_FORMAT_TYPE_MAX + 1] = {
        // XE_IMAGE_FORMAT_LAYOUT_8
        {RSS::SURFACE_FORMAT_R8_UINT,               RSS::SURFACE_FORMAT_R8_SINT,
         RSS::SURFACE_FORMAT_R8_UNORM,              RSS::SURFACE_FORMAT_R8_SNORM,
         SURFACE_FORMAT_UNDEFINED },
        // XE_IMAGE_FORMAT_LAYOUT_16
        {RSS::SURFACE_FORMAT_R16_UINT,              RSS::SURFACE_FORMAT_R16_SINT,
         RSS::SURFACE_FORMAT_R16_UNORM,             RSS::SURFACE_FORMAT_R16_SNORM,
         RSS::SURFACE_FORMAT_R16_FLOAT },
        // XE_IMAGE_FORMAT_LAYOUT_32
        {RSS::SURFACE_FORMAT_R32_UINT,              RSS::SURFACE_FORMAT_R32_SINT,
         RSS::SURFACE_FORMAT_R32_UNORM,             RSS::SURFACE_FORMAT_R32_SNORM,
         RSS::SURFACE_FORMAT_R32_FLOAT },
        // XE_IMAGE_FORMAT_LAYOUT_8_8
        {RSS::SURFACE_FORMAT_R8G8_UINT,             RSS::SURFACE_FORMAT_R8G8_SINT,
         RSS::SURFACE_FORMAT_R8G8_UNORM,            RSS::SURFACE_FORMAT_R8G8_SNORM,
         SURFACE_FORMAT_UNDEFINED },
        // XE_IMAGE_FORMAT_LAYOUT_8_8_8_8
        {RSS::SURFACE_FORMAT_R8G8B8A8_UINT,         RSS::SURFACE_FORMAT_R8G8B8A8_SINT,
         RSS::SURFACE_FORMAT_R8G8B8A8_UNORM,        RSS::SURFACE_FORMAT_R8G8B8A8_SNORM,
         SURFACE_FORMAT_UNDEFINED },
        // XE_IMAGE_FORMAT_LAYOUT_16_16
        {RSS::SURFACE_FORMAT_R16G16_UINT,           RSS::SURFACE_FORMAT_R16G16_SINT,
         RSS::SURFACE_FORMAT_R16G16_UNORM,          RSS::SURFACE_FORMAT_R16G16_SNORM,
         RSS::SURFACE_FORMAT_R16G16_FLOAT },
        // XE_IMAGE_FORMAT_LAYOUT_16_16_16_16
        {RSS::SURFACE_FORMAT_R16G16B16A16_UINT,     RSS::SURFACE_FORMAT_R16G16B16A16_SINT,
         RSS::SURFACE_FORMAT_R16G16B16A16_UNORM,    RSS::SURFACE_FORMAT_R16G16B16A16_SNORM,
         RSS::SURFACE_FORMAT_R16G16B16A16_FLOAT },
        // XE_IMAGE_FORMAT_LAYOUT_32_32
        {RSS::SURFACE_FORMAT_R32G32_UINT,           RSS::SURFACE_FORMAT_R32G32_SINT,
         RSS::SURFACE_FORMAT_R32G32_UNORM,          RSS::SURFACE_FORMAT_R32G32_SNORM,
         RSS::SURFACE_FORMAT_R32G32_FLOAT },
        // XE_IMAGE_FORMAT_LAYOUT_32_32_32_32
        {RSS::SURFACE_FORMAT_R32G32B32A32_UINT,     RSS::SURFACE_FORMAT_R32G32B32A32_SINT,
         RSS::SURFACE_FORMAT_R32G32B32A32_UNORM,    RSS::SURFACE_FORMAT_R32G32B32A32_SNORM,
         RSS::SURFACE_FORMAT_R32G32B32A32_FLOAT },
        // XE_IMAGE_FORMAT_LAYOUT_10_10_10_2
        {RSS::SURFACE_FORMAT_R10G10B10A2_UINT,     RSS::SURFACE_FORMAT_R10G10B10A2_SINT,
         RSS::SURFACE_FORMAT_R10G10B10A2_UNORM,    RSS::SURFACE_FORMAT_R10G10B10A2_SNORM,
         //RSS::SURFACE_FORMAT_R10G10B10_FLOAT_A2_UNORM }, //TODO gen9 doesn't have FLOAT
         SURFACE_FORMAT_UNDEFINED },
        // XE_IMAGE_FORMAT_LAYOUT_11_11_10
        {SURFACE_FORMAT_UNDEFINED,                  SURFACE_FORMAT_UNDEFINED,
         SURFACE_FORMAT_UNDEFINED,                  SURFACE_FORMAT_UNDEFINED,
         RSS::SURFACE_FORMAT_R11G11B10_FLOAT },
        // XE_IMAGE_FORMAT_LAYOUT_5_6_5
        // TODO Use SURFACE_FORMAT_B5G6R5_UNORM?
        {SURFACE_FORMAT_UNDEFINED,                  SURFACE_FORMAT_UNDEFINED,
         SURFACE_FORMAT_UNDEFINED,                  SURFACE_FORMAT_UNDEFINED,
         SURFACE_FORMAT_UNDEFINED },
        // XE_IMAGE_FORMAT_LAYOUT_5_5_5_1
        //TODO use SURFACE_FORMAT_B5G5R5A1_UNORM?
        {SURFACE_FORMAT_UNDEFINED,                  SURFACE_FORMAT_UNDEFINED,
         SURFACE_FORMAT_UNDEFINED,                  SURFACE_FORMAT_UNDEFINED,
         SURFACE_FORMAT_UNDEFINED },
        // XE_IMAGE_FORMAT_LAYOUT_4_4_4_4
        //TODO use BGRA or ABGR formats?
        {SURFACE_FORMAT_UNDEFINED,                  SURFACE_FORMAT_UNDEFINED,
         SURFACE_FORMAT_UNDEFINED,                  SURFACE_FORMAT_UNDEFINED,
         SURFACE_FORMAT_UNDEFINED },
        // XE_IMAGE_FORMAT_LAYOUT_Y8
        {SURFACE_FORMAT_UNDEFINED,                  SURFACE_FORMAT_UNDEFINED,
         SURFACE_FORMAT_UNDEFINED,                  SURFACE_FORMAT_UNDEFINED,
         SURFACE_FORMAT_UNDEFINED },
        // XE_IMAGE_FORMAT_LAYOUT_NV12
        {SURFACE_FORMAT_UNDEFINED,                  SURFACE_FORMAT_UNDEFINED,
         SURFACE_FORMAT_UNDEFINED,                  SURFACE_FORMAT_UNDEFINED,
         SURFACE_FORMAT_UNDEFINED },
        // XE_IMAGE_FORMAT_LAYOUT_YUYV
        {SURFACE_FORMAT_UNDEFINED,                  SURFACE_FORMAT_UNDEFINED,
         SURFACE_FORMAT_UNDEFINED,                  SURFACE_FORMAT_UNDEFINED,
         SURFACE_FORMAT_UNDEFINED },
        // XE_IMAGE_FORMAT_LAYOUT_VYUY
        {SURFACE_FORMAT_UNDEFINED,                  SURFACE_FORMAT_UNDEFINED,
         SURFACE_FORMAT_UNDEFINED,                  SURFACE_FORMAT_UNDEFINED,
         SURFACE_FORMAT_UNDEFINED },
        // XE_IMAGE_FORMAT_LAYOUT_YVYU
        {SURFACE_FORMAT_UNDEFINED,                  SURFACE_FORMAT_UNDEFINED,
         SURFACE_FORMAT_UNDEFINED,                  SURFACE_FORMAT_UNDEFINED,
         SURFACE_FORMAT_UNDEFINED },
        // XE_IMAGE_FORMAT_LAYOUT_UYVY
        {SURFACE_FORMAT_UNDEFINED,                  SURFACE_FORMAT_UNDEFINED,
         SURFACE_FORMAT_UNDEFINED,                  SURFACE_FORMAT_UNDEFINED,
         SURFACE_FORMAT_UNDEFINED },
        // XE_IMAGE_FORMAT_LAYOUT_AYUV
        {SURFACE_FORMAT_UNDEFINED,                  SURFACE_FORMAT_UNDEFINED,
         SURFACE_FORMAT_UNDEFINED,                  SURFACE_FORMAT_UNDEFINED,
         SURFACE_FORMAT_UNDEFINED },
        // XE_IMAGE_FORMAT_LAYOUT_YUAV
        {SURFACE_FORMAT_UNDEFINED,                  SURFACE_FORMAT_UNDEFINED,
         SURFACE_FORMAT_UNDEFINED,                  SURFACE_FORMAT_UNDEFINED,
         SURFACE_FORMAT_UNDEFINED },
        // XE_IMAGE_FORMAT_LAYOUT_P010
        {SURFACE_FORMAT_UNDEFINED,                  SURFACE_FORMAT_UNDEFINED,
         SURFACE_FORMAT_UNDEFINED,                  SURFACE_FORMAT_UNDEFINED,
         SURFACE_FORMAT_UNDEFINED },
        // XE_IMAGE_FORMAT_LAYOUT_Y410
        {SURFACE_FORMAT_UNDEFINED,                  SURFACE_FORMAT_UNDEFINED,
         SURFACE_FORMAT_UNDEFINED,                  SURFACE_FORMAT_UNDEFINED,
         SURFACE_FORMAT_UNDEFINED },
        // XE_IMAGE_FORMAT_LAYOUT_P012
        {SURFACE_FORMAT_UNDEFINED,                  SURFACE_FORMAT_UNDEFINED,
         SURFACE_FORMAT_UNDEFINED,                  SURFACE_FORMAT_UNDEFINED,
         SURFACE_FORMAT_UNDEFINED },
        // XE_IMAGE_FORMAT_LAYOUT_Y16
        {SURFACE_FORMAT_UNDEFINED,                  SURFACE_FORMAT_UNDEFINED,
         SURFACE_FORMAT_UNDEFINED,                  SURFACE_FORMAT_UNDEFINED,
         SURFACE_FORMAT_UNDEFINED },
        // XE_IMAGE_FORMAT_LAYOUT_P016
        {SURFACE_FORMAT_UNDEFINED,                  SURFACE_FORMAT_UNDEFINED,
         SURFACE_FORMAT_UNDEFINED,                  SURFACE_FORMAT_UNDEFINED,
         SURFACE_FORMAT_UNDEFINED },
        // XE_IMAGE_FORMAT_LAYOUT_Y216
        {SURFACE_FORMAT_UNDEFINED,                  SURFACE_FORMAT_UNDEFINED,
         SURFACE_FORMAT_UNDEFINED,                  SURFACE_FORMAT_UNDEFINED,
         SURFACE_FORMAT_UNDEFINED },
        // XE_IMAGE_FORMAT_LAYOUT_P216
        {SURFACE_FORMAT_UNDEFINED,                  SURFACE_FORMAT_UNDEFINED,
         SURFACE_FORMAT_UNDEFINED,                  SURFACE_FORMAT_UNDEFINED,
         SURFACE_FORMAT_UNDEFINED },
        // XE_IMAGE_FORMAT_LAYOUT_P416
        {SURFACE_FORMAT_UNDEFINED,                  SURFACE_FORMAT_UNDEFINED,
         SURFACE_FORMAT_UNDEFINED,                  SURFACE_FORMAT_UNDEFINED,
         SURFACE_FORMAT_UNDEFINED },
    };

    const SHADER_CHANNEL_SELECT_ALPHA shaderChannelSelect[XE_IMAGE_FORMAT_SWIZZLE_MAX + 1] = {
        RSS::SHADER_CHANNEL_SELECT_ALPHA_RED,
        RSS::SHADER_CHANNEL_SELECT_ALPHA_GREEN,
        RSS::SHADER_CHANNEL_SELECT_ALPHA_BLUE,
        RSS::SHADER_CHANNEL_SELECT_ALPHA_ALPHA,
        RSS::SHADER_CHANNEL_SELECT_ALPHA_ZERO,
        RSS::SHADER_CHANNEL_SELECT_ALPHA_ONE,
        RSS::SHADER_CHANNEL_SELECT_ALPHA_ZERO, //X
    };

    bool initialize(Device *device, const xe_image_desc_t *desc) override;

    void copySurfaceStateToSSH(void *surfaceStateHeap, const uint32_t surfaceStateOffset) override;

  protected:
    RENDER_SURFACE_STATE surfaceState;
};

template <uint32_t gfxProductFamily>
struct ImageProductFamily;

} //namespace L0
