# 
# Copyright (C) 2023 Intel Corporation
#
# SPDX-License-Identifier: MIT
#

version: 2
updates:
  # Enable version updates for pip
  - package-ecosystem: "pip"
    # Look for `requirements.txt` `third_party` directory
    directory: "/third_party"
    # Check the pip registry for updates every week
    schedule:
      interval: "weekly"
    # Disable version updates for pip dependencies
    open-pull-requests-limit: 0
