import os
import util

"""
    calls the external cpp compiler; assumes environment/paths are already set
"""
def cl(filepath):
    cmdline = "cl /c %s"%filepath
    os.system(cmdline)

"""
Entry-point:
    compiles each source file generated by the scripts
"""
def compile_cpp_source(path, namespace, specs):
    cpp_path = os.path.join(path, "source")

    for s in specs:
        filename = "%s_%s.cpp"%(namespace, s['name'])
        filepath = os.path.join(cpp_path, filename)
        print("Compiling %s..."%filepath)
        cl(filepath)

    util.removeFiles(".", "*.obj")

